[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "types-mujoco"
version = "0.1.0"

[tool.setuptools]
packages = ["mujoco"]
include-package-data = true

[tool.setuptools.package-data]
"mujoco" = ["*.pyi"]
